### ISSUE TITLE
更新hassistant core-2021.4.0版本后，报错无法使用。日志报错如下：

### ISSUE THREAD

**Issue by 9609759** [tiandeyu/mijia_curtain#4]
Error while setting up mijia_curtain platform for cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 205, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mijia_curtain/cover.py", line 159, in setup_platform
    cover = MijiaCurtain(name, host, token, model)
  File "/config/custom_components/mijia_curtain/cover.py", line 255, in __init__
    self.miotDevice = MiotDevice(ip=host, token=token, mapping=self._mapping)
TypeError: __init__() got an unexpected keyword argument 'mapping'

**Comment by tiandeyu** [comment]
已修复
