### ISSUE TITLE
更新homeassistant  最新版本core-2021.4.0 后，无法使用，日志报错如下，

### ISSUE THREAD

**Issue by 9609759** [tiandeyu/mijia_curtain#5]
Error while setting up mijia_curtain platform for cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 205, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mijia_curtain/cover.py", line 159, in setup_platform
    cover = MijiaCurtain(name, host, token, model)
  File "/config/custom_components/mijia_curtain/cover.py", line 255, in __init__
    self.miotDevice = MiotDevice(ip=host, token=token, mapping=self._mapping)
TypeError: __init__() got an unexpected keyword argument 'mapping'

**Comment by tiandeyu** [comment]
需要等待ha更新python-miio到最新版

**Comment by tiandeyu** [comment]
docker环境进入homeassistant容器
docker exec -ti homeassistant bash
强制更新python-miio到最新版
pip install python-miio==0.5.5.2
