### ISSUE TITLE
python-miio  0.5.5.2 & core-2021.4.6 启动错误

### ISSUE THREAD

**Issue by HotdogWang** [tiandeyu/mijia_curtain#6]
您好

我的 HA 是在群晖中使用 docker 设定起来的
现在的版本号是 ”core-2021.4.6”

也照了您之前关闭的问题中
进入到 docker 里 并将 python-miio 升级到了 0.5.5.2 的版本
启动起来还是发生了下面的错误

```
Error while setting up mijia_curtain platform for cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 205, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mijia_curtain/cover.py", line 159, in setup_platform
    cover = MijiaCurtain(name, host, token, model)
  File "/config/custom_components/mijia_curtain/cover.py", line 260, in __init__
    self._mapping = get_mapping(self._model, self._mapping)
  File "/config/custom_components/mijia_curtain/cover.py", line 225, in get_mapping
    current_position_prop = [prop for prop in curtain_properties if ATTR_CURRENT_POSITION in prop['type']][0]
IndexError: list index out of range
```

**Comment by orionroad** [comment]
same here. mijia_curtain broken after update ha.core 2021.4.6

**Comment by tiandeyu** [comment]
已经修复这个问题了，更新到最新版本即可解决
