### ISSUE TITLE
更新homeassistant core-2021.9.1 版本后，窗帘又报错，麻烦大佬看下什么原因，报错信息如下

### ISSUE THREAD

**Issue by 9609759** [tiandeyu/mijia_curtain#9]
Logger: homeassistant.components.cover
Source: custom_components/mijia_curtain/cover.py:255
Integration: 卷帘 (documentation, issues)
First occurred: 13:19:10 (3 occurrences)
Last logged: 13:19:11

Error while setting up mijia_curtain platform for cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mijia_curtain/cover.py", line 159, in setup_platform
    cover = MijiaCurtain(name, host, token, model)
  File "/config/custom_components/mijia_curtain/cover.py", line 255, in __init__
    self.miotDevice = MiotDevice(ip=host, token=token)
  File "/usr/local/lib/python3.9/site-packages/miio/miot_device.py", line 50, in __init__
    raise DeviceException(
miio.exceptions.DeviceException: Neither the class nor the parameter defines the mapping

**Comment by tiandeyu** [comment]
我根据你提供的报错信息更新了一些，你试试好使不，我还没更新到9.1

**Comment by 9609759** [comment]
大佬你好，谢谢你更新了插件，我已经测试，不再报错，可以正常使用，非常感谢！

**Comment by tiandeyu** [comment]
感谢支持
